FROM node:22.11.0-alpine3.19

# Set the working directory
WORKDIR /app

# Enable yarn
RUN corepack enable

# Copy the package.json and yarn.lock files first, then install the npm packages
# taking advantage of Docker caching
COPY package.json yarn.lock ./
RUN yarn install

# Copy the application files, after installing the npm packages
COPY . .

# Expose the port
EXPOSE 8080

# Run the application
ENTRYPOINT [ "node", "server.js" ]