FROM ubuntu:24.04

# Install Node.js
ARG NODE_MAJOR=22

RUN apt-get update && \
  apt-get install -y ca-certificates curl gnupg && \
  mkdir -p /etc/apt/keyrings && \
  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
  apt-get update && \
  apt-get install -y nodejs

# Set the working directory
WORKDIR /app

# Copy the application files
COPY . .

# Install the npm packages
RUN npm install

# Expose the port
EXPOSE 8080

# Run the application
ENTRYPOINT [ "node", "server.js" ]