FROM node:22.11.0

# Set the working directory
WORKDIR /app

# Copy the application files
COPY . .

# Install the npm packages
RUN npm install

# Expose the port
EXPOSE 8080

# Run the application
ENTRYPOINT [ "node", "server.js" ]