apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  type: NodePort
  selector:
    app: conversao-temperatura
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
