services:
  postgres:
    image: postgres:12.17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-kubedevnews} # Environment variable with default value ( after :- )
    volumes:
      - postgres-vol:/var/lib/postgresql/data # Volume using docker volume
      # - ./postgres-data:/var/lib/postgresql/data # Volume using bind mount
    networks:
      - app-network

volumes:
  postgres-vol:
    # name: postgres-vol # Custom volume name
    # driver: local # Default driver
    # external: false # If true, it will not create a new volume if it does not exist