# build stage
FROM golang:1.23.1-alpine3.19 AS builder

WORKDIR /build

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# final stage
FROM alpine:3.19 AS app

WORKDIR /app

COPY --from=builder /build/main .

CMD ["./main"]